language: node_js  #設置語言

node_js: 6  #設置相應的版本

cache:
    apt: true
    directories:
        - node_modules # 緩存不經常更改的內容

before_install:
  - echo 安装hexo相关环境...

install:
  # - npm install -g cnpm --registry=https://registry.npm.taobao.org
  - npm install

before_script:
  - echo 清空缓存静态文件
  - echo 生成静态文件...

script:
  - echo 开始部署...
  - git init
  - git config --global user.name "${U_NAME}"  #修改name
  - git config --global user.email "${U_EMAIL}"  #修改email
  - git add ./
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名稱
  # Github Pages
  - git push --quiet "https://${GH_TOKEN}@${GH_REF}" master:master --tags
branches:
  only:
    - master
env:
 global:
   # Github Pages
   - GH_REF: github.com/github.com/lionker/web-notes

