language: node_js  

node_js: 6  

script: true

after_script:
  - cd ./webboo/_book
  - git init
  - git config user.name "lionker"
  - git config user.email "aaronhuangsnail@gmail.com"
  - git add .
  - git commit -m "Update tools"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
# E: Build LifeCycle

#指定分支，只有指定的分支(为本地分支)提交时才会运行脚本
branches:
  only:
    - master